#! /bin/bash

setenv() {
	# Source in env
	[ -f "$SOURCEDIR/lib/env" ] && . "$SOURCEDIR/lib/env"
	
	# Source in library
	LIB="$SOURCEDIR/lib"
	[ -d $LIB ] && for lib in $LIB/*; do . $lib; done
	
	# File that tracks the last person to chat with the chatterbox
	export f="/Users/family/.chatterbox"
	[ -f $f ] && . $f
}

# $1 - Desired variable name/command
# $2 - [Optional] var type (int|str)
getinput() {
	read varname vartype <<< $@
	read input
	# Check/run commands until there aren't any left
	while checkforcommands $input; do
		echo "Still a command"
		read input
	done
	# Say the input out loud; makes it more conversational
    say -v Junior $input 2>/dev/null

	# Declared variable types
	if [ -n "$vartype" ]; then
		# If it's supposed to be an int, make sure it is; otherwise ask again.
		if [ "$vartype" == "int" ]; then
			if [[ ! $input =~ ^[0-9]+$ ]]; then
				chatter "That's not even a number; try again."
				getinput $varname $vartype
			elif [ ${#input} -gt 20 ]; then
				chatter "That number is way too big for me to understand; try again."
				getinput $varname $vartype
			fi
		#elif [ "$vartype" == "str" ]; then
		fi
	fi

	eval $varname=\"$input\"
}

checkforcommands() {
	# Check to see if the input is a command.  If so, run the command.
	# If not, return false and continue
	cmd=$@
	case $cmd in
		exit|quit|leave|bye)
			chatter "Goodbye!"
			exit
		;;
		randomflag)
			chatter "Setting Random flag."
			export RANDOMFLAG=true
			return 0
		;;
		checkrandomflag)
			chatter "Random flag is currently: $RANDOMFLAG."
			return 0
		;;
		*)
			# Not a command; return false
			return 1
		;;
	esac
}

playgame() {
	chatter "Actually, I don't know any games yet.  Sorry!"
}

chatter() {
	echo $@
	[[ -x /usr/bin/say ]] && /usr/bin/say $@ 2>/dev/null
}

yesno() {
	getinput yesno
	if [[ "$yesno" =~ (^yes$|^y$|^Y$|^Yes$) ]]; then
		return 0
	elif [[ "$yesno" =~ (^no$|^n$|^N$|^No$) ]]; then
		return 1
	else
		chatter "Please answer 'yes' or 'no': "
		yesno
		return $?
	fi
}

